[features]
seeds = false
skip-lint = false
[programs.devnet]
mint_nft = "88b6N7f2vXTqYAo3SLQGB2ShM7ctrAoxuFA6XaUwWCAu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/elijah/solanaDevCourse/solana-movie-frontend/SDCcPraNtvK4XPk5XASqYExWyEPrH9YAnEwm6Hcuz3U.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test-mint = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-mint-and-print.ts"